platform :ios,'8.0'
target 'Abaaba' do

pod 'AFNetworking','~> 3.2.1'
pod 'SDWebImage', '~> 4.4.2'
pod 'Reachability', '~> 3.2'
pod 'TPKeyboardAvoiding', '~> 1.3.2'
pod 'MJRefresh', '~>3.1.15.3'
pod 'MJExtension', '~>3.0.15.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'JSONKit',  '~>1.4'
pod 'DeviceUtil', '~> 2.1.3'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'ALToastView', '~> 0.0.1'
pod 'DeviceUtil', '~> 2.1.3'


pod 'iConsole', '~> 1.5.3', :configurations => ['Debug']
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'Tweaks', :configurations => ['Debug'], :git => 'https://github.com/facebook/Tweaks.git'
pod 'JSONSyntaxHighlight', :configurations => ['Debug'], :git => 'https://github.com/bahamas10/JSONSyntaxHighlight.git'
pod 'OHHTTPStubs', :configurations => ['Debug']


end
